// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JournalEntrySchema
 */
export type JournalEntrySchema = {
    /**
     * Id
     */
    id: string;
    level: LogLevel;
    /**
     * Message
     */
    message: string;
    /**
     * Timestamp
     */
    timestamp: string;
    type: LogType;
};

/**
 * JournalResponse
 */
export type JournalResponse = {
    /**
     * Journal
     */
    journal: Array<JournalEntrySchema>;
};

/**
 * LaunchSchema
 */
export type LaunchSchema = {
    /**
     * Failed At
     */
    failed_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Aborted
     */
    is_aborted?: boolean | null;
    /**
     * Scheduled At
     */
    scheduled_at: string;
    /**
     * Scheduled By
     */
    scheduled_by: string;
    /**
     * Skipped At
     */
    skipped_at?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * LogLevel
 */
export type LogLevel = 'INFO' | 'WARNING' | 'ERROR';

/**
 * LogType
 */
export type LogType = 'UNCLASSIFIED' | 'FILE';

/**
 * ScheduleResponse
 */
export type ScheduleResponse = {
    /**
     * Tasks
     */
    tasks: Array<TaskSchema>;
};

/**
 * ScopeResponse
 */
export type ScopeResponse = {
    /**
     * Scope Id
     */
    scope_id: string;
};

/**
 * ScopedTaskStatus
 */
export type ScopedTaskStatus = 'NEW' | 'PENDING' | 'IN_PROGRESS' | 'SUCCESS' | 'FAILED' | 'SKIPPED';

/**
 * TaskListResponse
 */
export type TaskListResponse = {
    /**
     * Tasks
     */
    tasks: Array<TaskSchema>;
};

/**
 * TaskSchema
 */
export type TaskSchema = {
    current_launch?: LaunchSchema | null;
    /**
     * Depends On
     */
    depends_on: Array<string>;
    /**
     * Description
     */
    description: string;
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    latest_launch?: LaunchSchema | null;
    /**
     * Spec Id
     */
    spec_id: string;
    status: ScopedTaskStatus;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type InitScopeApiScopesScopeIdPostData = {
    body?: never;
    path: {
        /**
         * Scope Id
         */
        scope_id: string;
    };
    query?: never;
    url: '/api/scopes/{scope_id}';
};

export type InitScopeApiScopesScopeIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InitScopeApiScopesScopeIdPostError = InitScopeApiScopesScopeIdPostErrors[keyof InitScopeApiScopesScopeIdPostErrors];

export type InitScopeApiScopesScopeIdPostResponses = {
    /**
     * Successful Response
     */
    201: ScopeResponse;
};

export type InitScopeApiScopesScopeIdPostResponse = InitScopeApiScopesScopeIdPostResponses[keyof InitScopeApiScopesScopeIdPostResponses];

export type StopRunApiScopesScopeIdRunDeleteData = {
    body?: never;
    path: {
        /**
         * Scope Id
         */
        scope_id: string;
    };
    query?: never;
    url: '/api/scopes/{scope_id}/run';
};

export type StopRunApiScopesScopeIdRunDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopRunApiScopesScopeIdRunDeleteError = StopRunApiScopesScopeIdRunDeleteErrors[keyof StopRunApiScopesScopeIdRunDeleteErrors];

export type StopRunApiScopesScopeIdRunDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type StopRunApiScopesScopeIdRunDeleteResponse = StopRunApiScopesScopeIdRunDeleteResponses[keyof StopRunApiScopesScopeIdRunDeleteResponses];

export type GetTasksApiScopesScopeIdTasksGetData = {
    body?: never;
    path: {
        /**
         * Scope Id
         */
        scope_id: string;
    };
    query?: never;
    url: '/api/scopes/{scope_id}/tasks';
};

export type GetTasksApiScopesScopeIdTasksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTasksApiScopesScopeIdTasksGetError = GetTasksApiScopesScopeIdTasksGetErrors[keyof GetTasksApiScopesScopeIdTasksGetErrors];

export type GetTasksApiScopesScopeIdTasksGetResponses = {
    /**
     * Successful Response
     */
    200: TaskListResponse;
};

export type GetTasksApiScopesScopeIdTasksGetResponse = GetTasksApiScopesScopeIdTasksGetResponses[keyof GetTasksApiScopesScopeIdTasksGetResponses];

export type AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteData = {
    body?: never;
    path: {
        /**
         * Scope Id
         */
        scope_id: string;
        /**
         * Task Id
         */
        task_id: string;
        /**
         * Launch Id
         */
        launch_id: string;
    };
    query?: never;
    url: '/api/scopes/{scope_id}/tasks/{task_id}/launches/{launch_id}';
};

export type AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteError = AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteErrors[keyof AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteErrors];

export type AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteResponse = AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteResponses[keyof AbortTaskApiScopesScopeIdTasksTaskIdLaunchesLaunchIdDeleteResponses];

export type GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetData = {
    body?: never;
    path: {
        /**
         * Scope Id
         */
        scope_id: string;
        /**
         * Task Id
         */
        task_id: string;
        /**
         * Launch Id
         */
        launch_id: string;
    };
    query?: never;
    url: '/api/scopes/{scope_id}/tasks/{task_id}/launches/{launch_id}/journal';
};

export type GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetError = GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetErrors[keyof GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetErrors];

export type GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetResponses = {
    /**
     * Successful Response
     */
    200: JournalResponse;
};

export type GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetResponse = GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetResponses[keyof GetJournalApiScopesScopeIdTasksTaskIdLaunchesLaunchIdJournalGetResponses];

export type ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostData = {
    body?: never;
    path: {
        /**
         * Scope Id
         */
        scope_id: string;
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/scopes/{scope_id}/tasks/{task_id}/schedule';
};

export type ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostError = ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostErrors[keyof ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostErrors];

export type ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostResponses = {
    /**
     * Successful Response
     */
    202: ScheduleResponse;
};

export type ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostResponse = ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostResponses[keyof ScheduleTaskApiScopesScopeIdTasksTaskIdSchedulePostResponses];
